chore(husky): add error handling to pre-push

diff --git a/.cargo-husky/hooks/pre-push b/.cargo-husky/hooks/pre-push
--- a/.cargo-husky/hooks/pre-push
+++ b/.cargo-husky/hooks/pre-push
@@ -19,5 +19,17 @@
 # cog bump may fail with 'No commit found to bump current version'
 # set -e
 
-cog bump --auto
+# Check whether cocogitto is installed
+if ! cog bump --help >/dev/null; then
+    echo "error: please install cocogitto"
+    exit 1
+fi
+
+# Check whether cargo-bump is installed
+if ! cargo bump --help >/dev/null; then
+    echo "error: please install cargo-bump"
+    exit 1
+fi
+
+cog bump --auto >/dev/null
 exit 0
